### PR TITLE
allow running both rel_skill ensembles

### PR DESCRIPTION
**Pull request by sbfnk**
Some small modifications to allow running the relative skill ensemble both by horizon and overall to be able to then compare using #475. Not at all sure the string parsing used here is the best / most generalisable way, and happy to have it ditched for another way.

### CODE REVIEW

**Comment by kathsherratt** [comment]
Ah great, I was wondering whether/how to organise doing this, thank you! Will merge into the branch. 

In any case across all the ensemble code I think there is a little tweaking to do before it will really generalise, so I was planning to revisit when the structure around it is more settled.

**Comment by giudici** [comment]
Dear Kath, can you please unsubscribe me from this mailing list ? thanks
[image: LOGO-UNIPV]
Paolo Stefano Giudici
Professor of Statistics, Department of Economics and Management,
Coordinator of the European projects FIN-TECH and PERISCOPE
https://www.linkedin.com/in/paolo-giudici-60028a/


Il giorno gio 3 giu 2021 alle ore 18:07 Kath Sherratt <
***@***.***> ha scritto:

**Comment by kathsherratt** [comment]
Hi Paolo - sorry you are getting these notifications! 

I think Github has automatically subscribed you to all notifications for all new events/messages, which can happen when you fork and/or "Watch" the repository.

You should be able to manage this by changing the "Watch" setting. Click the "Unwatch" button at the top-right of any of the European repo Github pages, and change the Notifications setting from the drop-down menu. You should see the same options as in the image attached. (I cannot access this for you as it is directly associated with your Github account settings.)

I would recommend choosing the "Participating and @ mentions" option, so that you will get email notifications only when you are directly mentioned in any comment, issue, or pull request. 

Hope that fixes the problem.

Kath

image

**Comment by giudici** [comment]
Thank you!
[image: LOGO-UNIPV]
Paolo Stefano Giudici
Professor of Statistics, Department of Economics and Management,
Coordinator of the European projects FIN-TECH and PERISCOPE
https://www.linkedin.com/in/paolo-giudici-60028a/


Il giorno gio 3 giu 2021 alle ore 19:53 Kath Sherratt <
***@***.***> ha scritto:

**Pull request merged**
