### PR TITLE
Fix Switzerland hospitalisation data (#1359)

### PR DESCRIPTION
**Pull request by kathsherratt**
- Fix for #1359: Swiss hospitalisation data was stuck on a fixed date csv download.
- This uses the API for the same source, and the resulting daily values are identical, but now up to date.
- Many thanks for the code suggestion in the issue.

### CODE REVIEW

**Comment by sbfnk** [comment]
do we need to add installing `jsonlite` and `httr` to the action?

**Comment by kathsherratt** [comment]
Done. I'm sorry again for not noticing this mistake earlier.

**Review by sbfnk — APPROVED** [review]
Looks good, thanks. Looking at the daily data we might want to keep an eye on whether it might need truncation by a week or so.

```
Switzerland,CH,2021-12-06,114,Hub,Scraped
Switzerland,CH,2021-12-07,107,Hub,Scraped
Switzerland,CH,2021-12-08,106,Hub,Scraped
Switzerland,CH,2021-12-09,104,Hub,Scraped
Switzerland,CH,2021-12-10,107,Hub,Scraped
Switzerland,CH,2021-12-11,75,Hub,Scraped
Switzerland,CH,2021-12-12,69,Hub,Scraped
Switzerland,CH,2021-12-13,68,Hub,Scraped
Switzerland,CH,2021-12-14,15,Hub,Scraped
Switzerland,CH,2021-12-15,0,Hub,Scraped
```

**Comment by kathsherratt** [comment]
OK, I'll merge and re-run the data update to get this sorted for today, then check back (maybe we could re-run the automated hospitalisation data checker in the next few weeks too).

**Pull request merged**
