### PR TITLE
Temporary PR for testing validation

### PR DESCRIPTION
**Pull request by kathsherratt**
Temporary PR for testing purpose only (https://github.com/epiforecasts/covid19-forecast-hub-europe-validations/pull/12) - PR to be closed after use

### CODE REVIEW

**Comment by Bisaloo** [comment]
@kathsherratt, I updated the action file so that we can run code from any branch of `covid19-forecast-hub-europe` (alongside the current `main` version). I hope that's okay. It seems more helpful for the use cases I have in mind but if I missed something, feel free to revert :)

**Comment by Bisaloo** [comment]
Double checking that https://github.com/epiforecasts/covid19-forecast-hub-europe/pull/535 does not cause any issues.

**Comment by kathsherratt** [comment]
Checking validation update

**Comment by kathsherratt** [comment]
Testing that three of four csv files in this PR should be valid, with one invalid.

All csv filenames use the `forecast_date` of that csv (which we check elsewhere in validation).

Valid files:
- `2021-02-15-EuroCOVIDhub-ensemble.csv` - `forecast_date: 2021-02-15` (monday) and `1 wk ahead` `target_end_date: 2021-02-20` (saturday same week)
- `2021-02-17...` (wednesday) with target end date 2021-02-27 (saturday week following)
- `2021-03-01...` (monday) with target end date 2021-03-06 (saturday same week, unchanged file used in testing)

Invalid: 
- `2021-02-16-EuroCOVIDhub-ensemble.csv`, which has forecast date 2021-02-16 (tuesday) and 1 week target end date 2021-02-20 (saturday same week)

Build correctly fails to validate the `2021-02-16` forecast with 1 wk target end date `2021-02-20`:

image

This confirms that the code for any day submissions is working from PR https://github.com/epiforecasts/covid19-forecast-hub-europe-validations/pull/22 

Removing files to keep this PR clean for future testing.

**Comment by kathsherratt** [comment]
Validation correctly marks `inc hosp` targets as valid in locations where `data-truth/locations_eu.csv` has any value (of source data) for the column `inc_hosp`; and invalid in locations where this value is missing.

**Pull request closed without merging**
