### PR TITLE
Score forecasts relative to baseline

### LINKED ISSUE #614: Score relative to baseline model
Now that we have a baseline model implemented it would be good to compute the relative skills of forecasts relative to that model. To do that we need to 

1) Generate baseline forecasts for all past dates
2) Change all calls to `eval_forecasts` that set `compute_relative_skill=TRUE` to also set `baseline="EuroCOVIDhub-baseline"`
3) Re-score all past forecasts by setting `re_run=TRUE` before running `code/evaluation/score_models.r`:
https://github.com/epiforecasts/covid19-forecast-hub-europe/blob/04c266cbc176f0efbc744611550b7b53cf78c01e/code/evaluation/score_models.r#L135
NB: The re-scoring is going to happen in #603 too

### PR DESCRIPTION
**Pull request by Bisaloo**
Fix #614 

~~I just created the previous baselines for now. I'm waiting for #577 to be merged before making any more changes to the reports to avoid conflicts.~~

### CODE REVIEW

**Review by sbfnk — APPROVED** [review]
All looks good to me.

**Comment by Bisaloo** [comment]
Holding off from merging since I don't have the expectation that @sbfnk mentioned during our meeting: `rel_skill` of 1 for `EuroCOVIDhub-baseline`. So there might be something wrong.

image

**Comment by Bisaloo** [comment]
We do have 1 in the `scaled_rel_skill` column:

|model                         |target_variable | interval_score| sharpness| underprediction| overprediction| coverage_deviation|      bias|      aem| relative_skill| scaled_rel_skill|
|:-----------------------------|:---------------|--------------:|---------:|---------------:|--------------:|------------------:|---------:|--------:|--------------:|----------------:|
|EuroCOVIDhub-baseline         |inc case        |       3222.550|  545.4794|        989.2970|      1687.7737|         -0.1385014| 0.2805106| 4568.921|      1.2441044|        1.0000000|
|EuroCOVIDhub-ensemble         |inc case        |       2175.638| 1169.9930|        326.1666|       679.4788|          0.0533580| 0.2021064| 3294.964|      0.7596762|        0.6106209|
|IEM_Health-CovidProject       |inc case        |       3198.605| 1484.2524|        368.4335|      1345.9195|         -0.0492828| 0.2760256| 4986.637|      1.1273412|        0.9061468|
|ILM-EKF                       |inc case        |       2640.637|  916.3243|        676.0886|      1048.2241|         -0.0095801| 0.1769936| 4032.804|      0.8516163|        0.6845216|
|USC-SIkJalpha                 |inc case        |       3425.975| 1319.1909|        799.7308|      1307.0533|         -0.1900278| 0.2563830| 4315.613|      1.2683968|        1.0195260|
|epiforecasts-EpiExpert        |inc case        |       4623.611| 1173.4491|       1426.3465|      2023.8155|         -0.1238973| 0.2309326| 6868.233|      0.9173704|        0.7373741|
|epiforecasts-EpiNow2          |inc case        |       2756.906| 1470.5582|        432.1728|       854.1749|         -0.0123077| 0.1331624| 4396.639|      0.9973977|        0.8016994|
|DSMPG-bayes                   |inc case        |       3381.194| 1222.2419|        254.5522|      1904.4002|         -0.0189460| 0.2771861| 5207.636|      0.8368722|        0.6726704|
|UMass-SemiMech                |inc case        |       3424.820| 1583.3761|       1064.1916|       777.2524|          0.0047978| 0.2481941| 4537.779|      1.3518611|        1.0866139|
|epiforecasts-EpiExpert_Rt     |inc case        |       3209.491| 1703.8881|        567.0170|       938.5860|          0.0104978| 0.1333333| 4695.913|      0.9116973|        0.7328141|
|epiforecasts-EpiExpert_direct |inc case        |       4378.156| 1179.3424|        249.5174|      2949.2965|         -0.1817391| 0.4808000| 6228.400|      0.9858359|        0.7924061|
|MUNI-ARIMA                    |inc case        |       1247.134|  471.8979|        189.3962|       585.8402|          0.0412740| 0.2495814| 1782.121|      0.8237979|        0.6621614|
|RobertWalraven-ESG            |inc case        |       1758.239|  475.9754|        318.6916|       963.5724|         -0.0728074| 0.2639073| 2605.728|      1.4103819|        1.1336524|

Do we want this column instead of `relative_skill`?

**Comment by sbfnk** [comment]
Ah yes, it seems that specifying a baseline creates an extra column rather than replacing the exiting `rel_skill` which is what I thought:

https://github.com/epiforecasts/scoringutils/blob/401f5a8c5f9d9d6806229bcfaf0bb0b9732f7641/R/pairwise-comparisons.R#L302

So yes, we want `scaled_rel_skill`.

**Comment by kathsherratt** [comment]
@Bisaloo , would it make sense if we merge #602 into main, merge main into this PR, and then re-run the evaluation part of this PR before merging? 

#602 changes the ensemble forecasts so they will need to be re-scored at some point - I thought perhaps we can just do this in one go here. Otherwise we can re-run the evaluation again after both this and #602 are merged.

**Review by kathsherratt — APPROVED** [review]

**Comment by Bisaloo** [comment]
I don't have any preference so feel free to do as you see fit and let me know if I should merge & re-run.

**Pull request merged**
