### PR TITLE
Latest predictions from MIMUW (team from GER-POL)

### PR DESCRIPTION
**Pull request by storaged**

### CODE REVIEW

**Comment by sbfnk** [comment]
Hi - happy to add this but you'll need to remove "Poland-" from the filename.

**Comment by storaged** [comment]
Hi, and I would be very happy to get it merged :)
Is the rename I made sufficient and visible for you or should I make something more?

**Comment by storaged** [comment]
Oops, there is something wrong with formatting.... gotta double-check it, sorry for these problems, I hope to solve it and commit quickly

**Comment by storaged** [comment]
> Hi - happy to add this but you'll need to remove "Poland-" from the filename.

Dear Sebastian, 

as I stated in one comment, I know that the deadline has passed. However, if by any chance you could merge it would be great. Next week the file will hopefully be pulled smoothly without any problem.

**Comment by sbfnk** [comment]
Of course! Thanks very much for your contribution.

**Pull request merged**
