### PR TITLE
Add hospitalisations to reports

### PR DESCRIPTION
**Pull request by Bisaloo**
I'm really not happy about this fix. The goal would be for everything to work when we change the config file, without having to keep a dictionary with nice labels for plots. The solution would be to use the nice labels directly in the raw data instead of abbreviated terms ('hosp') and to split 'inc case' into 'inc' and 'case'. Related: #708 and #796  

To do before it's ready to merge:

- [x] ~~Check why ensemble doesn't include hospitalisations and fix it.~~ As Seb suggested, we just needed to have a least 4 consecutive weeks of submission for this target.

### CODE REVIEW

**Comment by Bisaloo** [comment]
This seems to be working fine on my computer. Screenshots below

Screen Shot 2021-09-07 at 14 01 57-fullpage

Screen Shot 2021-09-07 at 14 09 01-fullpage

**Comment by Bisaloo** [comment]
Hmm, noticing just now that hospitalizations are still missing from scores

**Comment by Bisaloo** [comment]
The problem is that data from the ECDC doesn't use the same week origin as our forecast. They use Saturday and we use Monday. So when we merge the forecast and the truth data, they are not matched correctly, as shown in the table below:

```r
knitr::kable(data[10679:10685, ])
```

|location |target_variable |target_end_date |location_name | population| true_value|model                 |forecast_date |horizon |temporal_resolution |type     | quantile| prediction|
|:--------|:---------------|:---------------|:-------------|----------:|----------:|:---------------------|:-------------|:-------|:-------------------|:--------|--------:|----------:|
|BE       |inc hosp        |2021-08-21      |Belgium       |   11372068|        414|NA                    |NA            |NA      |NA                  |NA       |       NA|         NA|
|BE       |inc hosp        |2021-08-28      |Belgium       |   11372068|        419|NA                    |NA            |NA      |NA                  |NA       |       NA|         NA|
|BE       |inc hosp        |2021-09-04      |Belgium       |   11372068|        470|NA                    |NA            |NA      |NA                  |NA       |       NA|         NA|
|BE       |inc hosp        |2021-09-11      |Belgium       |   11372068|         NA|EuroCOVIDhub-ensemble |2021-09-06    |1       |wk                  |point    |       NA|        474|
|BE       |inc hosp        |2021-09-11      |Belgium       |   11372068|         NA|EuroCOVIDhub-ensemble |2021-09-06    |1       |wk                  |quantile |    0.010|        270|
|BE       |inc hosp        |2021-09-11      |Belgium       |   11372068|         NA|EuroCOVIDhub-ensemble |2021-09-06    |1       |wk                  |quantile |    0.025|        304|
|BE       |inc hosp        |2021-09-11      |Belgium       |   11372068|         NA|EuroCOVIDhub-ensemble |2021-09-06    |1       |wk                  |quantile |    0.050|        328|

How can we solve this? :thinking:

**Comment by Bisaloo** [comment]
This is probably what's causing the issue in the visualization app as well.

**Comment by kathsherratt** [comment]
Thanks for looking at this Hugo :) Is the hospitalisation data currently coming from `covidHubUtils::load_truth()`? In the original source ECDC use a Monday-Sunday week, but in either covidHubUtils or our download script I think we load it as a Sunday-Saturday week, in order to match case/death data. This is off the top of my head but may be worth exploring as the raw ECDC data are daily so we really should be able to get the weeks to align.

**Comment by Bisaloo** [comment]
Ah, based on previous conversations, I thought it was a feature and we had to find some kind of interpolation solution. But good to know it's likely a bug :+1:. I'll look into it.

**Comment by Bisaloo** [comment]
Ah my bad, I got confused over nothing. All is fine and as soon as we have truth data for the current week, evaluation reports should work as expected. I'm going to wait until next week to double check and then request a review.

**Comment by Bisaloo** [comment]
Yes, everything works fine now. I'm putting this on hold until we have one more model with hospitalisations, as agreed during the call with the ECDC. But it's ready for review and to be merged otherwise.

Screen Shot 2021-09-17 at 09 12 31-fullpage

**Comment by Bisaloo** [comment]
It's currently failing for Karlen-pypm because the ensemble has not yet been built for this week. I need to figure out how to gracefully handle this situation and make sure it doesn't interrupt the whole process.

**Pull request merged**
