### PR TITLE
2021-04-26 PL_GrzegorzRedlarski DistritsSum, first submission 

### PR DESCRIPTION
**Pull request by gr3gr3**

### CODE REVIEW

**Comment by kathsherratt** [comment]
Hi @gr3gr3 - Thanks for contributing! The validation check failed, but your formatting looks fine to me. The only potential issue I can spot that might be causing the error, is an empty line at the end of the metadata file. Please could you try deleting the empty line? (The validation will run automatically after a new commit.)
Kath

**Comment by kathsherratt** [comment]
Looks good. I think you should just need to remove the duplicate files to get this ready as there are now two `PL_GrzegorzRedlarski-DistritsSum` folders. We can only merge files into the `data-processed` directory. Please keep only the `data-processed\PL_GrzegorzRedlarski-DistritsSum` folder, and remove the other files (that are directly in the main repository). Thanks!

**Comment by gr3gr3** [comment]
These are my first steps on GitHub. I will try to resend the corrected file.

**Comment by sbfnk** [comment]
Hi, two things:
1) as Kath said, you seem to have two versions of the forecasts: one in the main directory, and one in the `data-processed` folder. Please remove the one from the main directory, as we need everything to be inside `data-processed`
2) I think there is a subtle spelling mismatch: the directory and forecast file are called `DistritsSum` and the metadata `DistrictsSum`. I think because of this the validator can't associate the metadata with the forecast.

**Comment by kathsherratt** [comment]
Thanks for fixing this up @gr3gr3! All looks good so no further action needed on your side.

**Comment by gr3gr3** [comment]
Thank you very much for all your help!

**Pull request merged**
