### PR TITLE
2021-10-04 - EpiForecast submission

### PR DESCRIPTION
**Pull request by seabbs**
This is an automated submission.

### CODE REVIEW

**Comment by seabbs** [comment]
Missing crowd forecasts this week 😢 @nikosbosse I stepped through the code and there is nothing in the tables that are being downloaded? Perhaps no submissions this week?

**Comment by seabbs** [comment]
:crying:

Screenshot 2021-10-04 at 22 15 03

**Comment by kathsherratt** [comment]
Merging, feel free to open another PR with the crowd forecast if it gets fixed.

**Comment by Bisaloo** [comment]
Posting this here in addition to slack in case anyone is monitoring this issue and wants to know where the file was moved:

https://covid19forecasthubcdn.blob.core.windows.net/data/truth_to_plot.csv

**Pull request merged**
