### PR TITLE
ULZF team

### PR DESCRIPTION
**Pull request by janezz25**

### CODE REVIEW

**Comment by kathsherratt** [comment]
Hi @janezz25 - welcome to the European Forecast Hub and thank you for submitting! This looks great. You have until Monday in case you want to update your forecast in any way. 

You and any members of your team are also very welcome to join the mailing list for participants in the Forecast Hub. We mainly use this to send invites to a weekly meeting open to anyone involved in the Hub, which you are welcome to attend. We usually discuss the latest week's forecasts and have a presentation from a contributing team. 

If you would be interested, please just request to join the email list to receive updates on this (putting your team name in the "reason for joining" box), here: 
https://groups.google.com/u/1/g/euro-covid19-forecast-hub

Best wishes,
Kath

**Comment by janezz25** [comment]
I'm not sure, if the updated files are uploaded to the main branch successfully.
I still not see my data in the main data-processed folder of the main branch. 
I followed the steps, but I’m not sure if I understand all correctly. 
Please give me some feedback if everything is ok. 

Best regards,
Janez

**Comment by kathsherratt** [comment]
Hi Janez (@janezz25), sorry for the delay getting back to you. This is great, the validation checks have passed, so you don't need to do anything else for this week's forecasts. 

For information, we merge all the forecasts into the main hub repository from all teams together on Tuesday mornings, around 11.30 CET (so this PR will be open until then). Then we create the ensemble model and build the website. So you should be able to see your forecasts on the [website](https://covid19forecasthub.eu/visualisation.html) by around 1300 CET. 

I've added you to the email list, please feel free to join the weekly calls at 1400 CET Wednesdays.

Thanks very much again!
Kath

**Comment by janezz25** [comment]
Dear Kath,

Sorry to bothering you. But since it’s my first time to participate in the hub, I have still some questions regarding visualisation of data from my model.
I’ve checked the website and I still don’t see my model listed in forecasts for Slovenia.
Did I miss something or is something wrong with my data.

Thnak you fro your help.
Best regards,
Janez

**Comment by sbfnk** [comment]
The model will usually appear in the visualisations on Tuesday afternoon here, see e.g. https://covid19forecasthub.eu/visualisation.html?location=SI&models=EuroCOVIDhub-ensemble&models=ULZF-SEIRC19SI&target=hosp

One the model has been submitted for four continuous weeks, it will appear in the evaluation reports at https://covid19forecasthub.eu/reports.html

**Pull request merged**
