### PR TITLE
Sophie Meakin's automated submission

### PR DESCRIPTION
**Pull request by sbfnk**

### CODE REVIEW

**Comment by Bisaloo** [comment]
Redundant with #1198 but it should work next time :grimacing:. Sorry about this.

**Comment by Bisaloo** [comment]
Actually, this might be better than #1198 because https://github.com/epiforecasts/covid19-forecast-hub-europe/commit/2809ede0aa2692c9409ee1ded0b7dd9c97eceaa0 was added in the meantime and this causes a huge difference in hospitalization forecasts for Switzerland.

**Review by sophiemeakin — COMMENTED** [review]
All looks good 👍🏻

**Comment by kathsherratt** [comment]
> Actually, this might be better than #1198 because [2809ede](https://github.com/epiforecasts/covid19-forecast-hub-europe/commit/2809ede0aa2692c9409ee1ded0b7dd9c97eceaa0) was added in the meantime and this causes a huge difference in hospitalization forecasts for Switzerland.

We will exclude Switzerland this week - #1197 - so shouldn't be a problem either way, but all fine anyway.

**Pull request merged**
