### PR TITLE
Try to speed up package installation in R-based GH actions

### PR DESCRIPTION
**Pull request by Bisaloo**
This is a first attempt at speeding up package installation in R-based GH actions. I might have to revisit it because:

- I've had some troubles getting RStudio Package Manager to actually deliver binaries on Linux in the past
- The achieved speed up might not be sufficient. In that case, I can add a caching step to avoid re-downloading / re-installing these packages each time

### CODE REVIEW

**Comment by sbfnk** [comment]
Cool! Is the best way to test it is to merge and give it a go? The forecasts come in Saturday-Tuesday so between now and the end of the week is a good time to try potentially breaking changes.

**Comment by Bisaloo** [comment]
Yes, I think that'd be the best strategy. For the other changes, I can try to add some tests to limit the risk of breakage.

**Comment by sbfnk** [comment]
I'm getting a merge conflict - can you bring this up-to-date with `main`?

**Comment by Bisaloo** [comment]
I'm not sure what happened but looks like you already brought these changes to `main`. I guess we can just close this PR.

**Comment by sbfnk** [comment]
Shaved more than 10 minutes off the runtime of this (which failed for other reasons as there was nothing new to commit): https://github.com/epiforecasts/covid19-forecast-hub-europe/actions/workflows/ECDC.yml

Amazing!

**Pull request closed without merging**
