### PR TITLE
2021-03-01-RobertWalraven-ESG

### PR DESCRIPTION
**Pull request by RobertWalraven**
Start over again

### CODE REVIEW

**Comment by jbracher** [comment]
I think the problem is tht there is a stray metadata file directly in the data-processed folder.

**Comment by jbracher** [comment]
As I wanted to make sure the checks work I made a PR of my own with the extra file in question removed: https://github.com/epiforecasts/covid19-forecast-hub-europe/pull/65 That PR was successful. I suggest we just merge my PR and you create a fresh fork (otherwise you'll probably run into a lot of github issues). Is that fine with you, @RobertWalraven ?

**Comment by RobertWalraven** [comment]
I removed the extraneous file.  It was uploaded accidentally when I was first trying uploads and I forgot about it.  I think my fork should be ok now, but if you want to do the merge, that is ok with me.

**Comment by jbracher** [comment]
I'll just merge your PR. I think it should be fine then.

**Pull request merged**
