### PR TITLE
2021-03-15 HZI-AgeExtendedSEIR

### PR DESCRIPTION
**Pull request by istirodiah**

### CODE REVIEW

**Comment by kathsherratt** [comment]
Hi @istirodiah - thank you for submitting to the European forecast hub!

There is a small logistical problem with the PR before we can get this merged. It looks like your csv and metadata files are currently stored directly within the `data-processed` folder. However these need to be stored inside a new folder within `data-processed`, named as your team name. Please see the guide [here](https://github.com/epiforecasts/covid19-forecast-hub-europe/wiki/Creating-a-team-directory), or have a look at the [data-processed](https://github.com/epiforecasts/covid19-forecast-hub-europe/tree/main/data-processed) folder for examples.

Best wishes,
Kath

**Comment by kathsherratt** [comment]
Hi @istirodiah , thanks for creating the new folder! Please could you move your csv and metadata files into it (it looks like they are currently still in the `data-processed` folder)? That should trigger the remaining formatting checks, which need to run before we can merge this in.
Kath

**Comment by istirodiah** [comment]
> Hi @istirodiah , thanks for creating the new folder! Please could you move your csv and metadata files into it (it looks like they are currently still in the `data-processed` folder)? That should trigger the remaining formatting checks, which need to run before we can merge this in.
> Kath

Hi @kathsherratt, it is just a file. How can I make a folder there?
Before I follow the instruction for submission via website. It says that "This may look like the files are uploaded separately, but it will actually create the folder." So I think it will automatically become a folder.

**Comment by kathsherratt** [comment]
Thanks for fixing this @istirodiah , this is good to go 👍

**Pull request merged**
