### PR TITLE
2021-02-28-RobertWalraven-ESG

### PR DESCRIPTION
**Pull request by RobertWalraven**
First upload of data

### CODE REVIEW

**Comment by jbracher** [comment]
Hi Robert, we fixed something on our end. Could you close and re-open this PR so the validation checks are re-started? Thanks a lot!

**Comment by jbracher** [comment]
It looks like the checks worked this time. However, there is a spare row with column names halfway down the file, maybe a problem when merging multiple files. Could you remove that and re-try? Thanks a lot!

**Comment by RobertWalraven** [comment]
Yes, it is working now.  I saw the problem in my metafile and data csv and am fixing those now.   Getting things to work the first time is always the hardest.

**Comment by RobertWalraven** [comment]
Cancel pull request

**Pull request closed without merging**
